name: CI

on: [push, pull_request]

jobs:
  Commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Validate current commit
        if: github.event_name == 'push'
        run: pnpm commitlint --from HEAD~1 --to HEAD --verbose
      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: pnpm commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
